services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: comments-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd
    ports:
      - "1433:1433"
    networks:
      - comments-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comments-api
    ports:
      - "7092:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=_CommentsDb;User Id=sa;Password=StrongP@ssw0rd;TrustServerCertificate=True;

    depends_on:
      - sqlserver
    networks:
      - comments-network

networks:
  comments-network:
